# Generated by Django 3.1.1 on 2020-10-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.house'),
        ),
    ]
