# Generated by Django 3.1.1 on 2020-11-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffe_makers',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.code_ninja'),
        ),
        migrations.AlterField(
            model_name='game_of_pwns',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.code_ninja'),
        ),
        migrations.AlterField(
            model_name='python_slayer',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.code_ninja'),
        ),
        migrations.AlterField(
            model_name='samurai_c',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.code_ninja'),
        ),
        migrations.AlterField(
            model_name='score',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.code_ninja'),
        ),
    ]
