# Generated by Django 3.1.1 on 2020-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_auto_20201012_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='warning',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
