# Generated by Django 3.1.1 on 2020-10-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_auto_20201021_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='belt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
