# Generated by Django 3.1.1 on 2020-10-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0004_auto_20201021_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.house'),
        ),
    ]
